### ISSUE TITLE
Failed to create Multitrack for some midi files

### ISSUE THREAD

**Issue by djosix** [salu133445/pypianoroll#1]
First, thanks for your awesome project!

https://github.com/salu133445/pypianoroll/blob/c436465e23fb3f49c3e63978079d72bdd8d00afe/pypianoroll/multitrack.py#L752

Should it be `pm.time_signature_changes[idx+1].time` at this line?

```
Traceback (most recent call last):
  File "/Users/dorian/.anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
TypeError: '<' not supported between instances of 'TimeSignature' and 'TimeSignature'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 6, in <module>
    mt = ppr.Multitrack('1_15c2c8fe4f85f63fe32e8830c4a274fd.mid')
  File "/Users/dorian/.anaconda3/lib/python3.6/site-packages/pypianoroll/multitrack.py", line 84, in __init__
    self.parse_midi(filepath)
  File "/Users/dorian/.anaconda3/lib/python3.6/site-packages/pypianoroll/multitrack.py", line 644, in parse_midi
    collect_onsets_only, threshold, first_beat_time)
  File "/Users/dorian/.anaconda3/lib/python3.6/site-packages/pypianoroll/multitrack.py", line 754, in parse_pretty_midi
    pm.time_signature_changes[idx+1])
  File "/Users/dorian/.anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 1075, in searchsorted
    return _wrapfunc(a, 'searchsorted', v, side=side, sorter=sorter)
  File "/Users/dorian/.anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 67, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/Users/dorian/.anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 47, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
TypeError: '<' not supported between instances of 'TimeSignature' and 'TimeSignature'
```

**Comment by salu133445** [comment]
Yes. It should be `pm.time_signature_changes[idx+1].time`.
Thanks for pointing out.
